#!/usr/bin/env python
import sys
import unittest

from testmarkdowncode import TestMarkdownCode


def load_tests(loader, tests, pattern):
    test_cases = unittest.TestSuite()
    TestMarkdownCode.load_tests(test_cases)
    return test_cases

if __name__ == '__main__':
    for filename in sys.argv[1:]:
        if filename == '-':
            TestMarkdownCode.create_tests(sys.stdin.read())
        else:
            with open(filename) as fp:
                TestMarkdownCode.create_tests(fp.read())
    unittest.main(argv=sys.argv[:1])
